// Generated by CoffeeScript 1.10.0
var App, React, ReactDOM, fs, ipcRenderer;

React = require('react');

ReactDOM = require('react-dom');

ipcRenderer = require('electron').ipcRenderer;

fs = require('fs');

App = React.createClass({displayName: "App",
  getInitialState: function() {
    return {
      body: '',
      opacity: 100,
      saved: true,
      inverted: false
    };
  },
  componentDidMount: function() {
    var e, error;
    try {
      this.setState({
        body: fs.readFileSync('/Users/sean/Desktop/title.txt', 'utf8')
      });
    } catch (error) {
      e = error;
      console.log('no file');
    }
    ipcRenderer.on('file-save', (function(_this) {
      return function() {
        fs.writeFileSync('/Users/sean/Desktop/title.txt', _this.state.body);
        return _this.setState({
          saved: true
        });
      };
    })(this));
    return ipcRenderer.on('file-invert', (function(_this) {
      return function() {
        return _this.setState({
          inverted: !_this.state.inverted
        });
      };
    })(this));
  },
  changeBody: function(e) {
    return this.setState({
      body: e.target.value,
      saved: false
    });
  },
  changeOpacity: function(e) {
    return this.setState({
      opacity: e.target.value
    });
  },
  editFilename: function() {
    return alert('ok?');
  },
  render: function() {
    return React.createElement("div", {
      "className": 'container' + (this.state.inverted ? ' inverted' : ''),
      "style": {
        opacity: this.state.opacity / 100
      }
    }, React.createElement("div", {
      "className": 'title-bar'
    }, React.createElement("div", {
      "className": 'title',
      "onDoubleClick": this.editFilename
    }, "title.txt ", (this.state.saved ? '' : '*')), React.createElement("input", {
      "type": 'range',
      "min": 20,
      "max": 100,
      "value": this.state.opacity,
      "onChange": this.changeOpacity
    })), React.createElement("textarea", {
      "value": this.state.body,
      "onChange": this.changeBody
    }));
  }
});

ReactDOM.render(React.createElement(App, null), document.getElementById('app'));
